export const MySkills = [
    'Next.JS ❤',
    'Javascript ❤',
    'Typescript ❤',
    'React ❤',
    'React Router',
    'React Query',
    'URQL',
    'CSS',
    'TailwindCSS',
    'Svelte',
    'SvelteKit',
    'Atomic Design',
    'Responsive Design',
    'Flutter',
    'Node.JS',
    'Rest',
    'GraphQL',
    'HTML 5',
    'Wordpress',
    'Java',
    'Spring Boot',
    'JPA',
    'Hibernate',
    'PostgreSQL',
    'MongoDB',
    'DevOps',
    'Docker',
    'Git',
    'Github Actions',
    'Jira',
    'Confluence',
    'Scrum',
    'Scrum Master',
    'Agile',
    'Kanban',
    'Linux ❤', // Pop up with "I use arch btw"
    'NeoVim ❤',
    'Tmux ❤',
];
